# Generated by Django 2.1.3 on 2018-12-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FlatName', models.CharField(max_length=100)),
                ('Address', models.TextField()),
                ('Descriptions', models.TextField()),
                ('City', models.CharField(max_length=100)),
            ],
        ),
    ]
