# Generated by Django 2.1.4 on 2018-12-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='document',
            fields=[
                ('doc_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('doc', models.TextField()),
                ('doc_content_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
