# Generated by Django 2.1.4 on 2018-12-17 08:12

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tenant',
            fields=[
                ('tenant_id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('deposit_amount', models.PositiveIntegerField()),
                ('gst_no', models.CharField(blank=True, default=None, max_length=100)),
                ('acc_name', models.CharField(max_length=100)),
                ('acc_no', models.PositiveIntegerField()),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_branch_name', models.CharField(max_length=100)),
                ('ifsc_no', models.CharField(max_length=100)),
            ],
        ),
    ]
