# Generated by Django 2.1.4 on 2018-12-24 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leaserenewal', '0001_initial'),
        ('trancations', '0001_initial'),
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='rent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rent_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rent_paid_date', models.DateField()),
                ('date_to_pay', models.DateField()),
                ('paid_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maintenance_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bal_amt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lease_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id+', to='leaserenewal.leaserenewal')),
                ('payment_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id+', to='trancations.trancations')),
                ('tenant_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id+', to='tenant.tenant')),
            ],
        ),
    ]
