# Generated by Django 2.1.4 on 2018-12-18 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('area_id', models.AutoField(primary_key=True, serialize=False)),
                ('shop_office_no', models.PositiveIntegerField()),
                ('length_in_ft', models.PositiveIntegerField()),
                ('width_in_ft', models.PositiveIntegerField()),
                ('total_area', models.PositiveIntegerField()),
                ('rent_per_sqft', models.PositiveIntegerField()),
                ('total_rent', models.PositiveIntegerField()),
            ],
        ),
    ]
