# Generated by Django 2.1.4 on 2018-12-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tax_acc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tax_of_month', models.DateField()),
                ('tax_of_year', models.DateField()),
                ('tax_amt', models.PositiveIntegerField()),
                ('tax_paid_date', models.DateField()),
            ],
        ),
    ]
