# Generated by Django 2.1.3 on 2018-12-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='termination',
            fields=[
                ('terminationid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('leavingdate', models.DateField()),
                ('leavingreason', models.TextField()),
            ],
        ),
    ]
