# Generated by Django 2.1.3 on 2018-12-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Apartmentsid', models.IntegerField()),
                ('Maintenances_of_month', models.DateTimeField()),
                ('Maintenances_of_year', models.DateTimeField()),
                ('Maintenances_amount', models.DecimalField(max_digits=10, decimal_places=2)),
                ('Maintenances_paid_date', models.DateField()),
            ],
        ),
    ]
