# Generated by Django 2.1.3 on 2018-12-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='building',
            fields=[
                ('buildingname', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('cities', models.CharField(choices=[('hubli', 'HUBLI'), ('dharwad', 'DHARWAD'), ('karwar', 'KARWAR'), ('gadag', 'GADAG'), ('haveri', 'HAVERI')], default='True', max_length=10)),
                ('state', models.CharField(choices=[('karanantak', 'KARANANTAK'), ('tamilnadu', 'TAMILNADU'), ('andrapradesh', 'ANDRAPRADESH'), ('DEHLI', 'DEHLI'), ('mumbai', 'MUMBAI')], default='True', max_length=10)),
                ('zip', models.IntegerField()),
                ('landloardid', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
