# Generated by Django 2.1.4 on 2018-12-24 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('managment', '0006_auto_20181222_1022'),
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='leaserenewal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('property', models.CharField(choices=[('apartment', 'APARTMENT'), ('flat', 'FLAT')], default='True', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('KARANATAKA', 'KARANATAKA'), ('DEHLI', 'DEHLI'), ('HARIYANA', 'HARIYANA'), ('KERALA', 'KERALA'), ('TAMILNADU', 'TAMILNADU'), ('ANDHRA PRADESH', 'ANDHRA PRADESH'), ('TELANGANA', 'TELANGANA'), ('BIHARA', 'BIHARA'), ('MADHYA PRADESH', 'MADHYA PRADESH'), ('PUNJAB', 'PUNJBA'), ('GOA', 'GOA'), ('J&K', 'J&K'), ('Assam', 'ASSAM'), ('Chhattisgarh', 'CHHATTISGARH'), ('GUJARAT', 'GUJARAT'), ('Himachal Pradesh', 'HIMACHAL PRADESH'), ('Haryana', 'HARYANA'), ('Jharkhand', 'JHARKHAND'), ('Maharashtra', 'MAHARASHTA'), ('Manipur', 'MANIPUR'), ('Meghalaya', 'MEGHALAYA'), ('Mizoram', 'MIZORAM'), ('Nagaland', 'NAGALAND'), ('Odisha', 'ODISHA')], default='True', max_length=10)),
                ('pincode', models.IntegerField()),
                ('landlord_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_name+', to='managment.owner')),
                ('tenant_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_name+', to='tenant.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='renewal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('renewaldate', models.DateField()),
                ('renewalperiod', models.CharField(max_length=100)),
                ('lease_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='id+', to='leaserenewal.leaserenewal')),
            ],
        ),
    ]
