# Generated by Django 2.1.4 on 2018-12-22 06:27

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0003_auto_20181221_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='owner',
            name='phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128),
        ),
    ]
