# Generated by Django 2.1.4 on 2018-12-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0004_auto_20181222_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.TextField(default=True, max_length=258),
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'APARTMENT'), ('flat', 'FLAT'), ('single_family_home', 'SINGLE_FAMILY_HOME'), ('duplex_home', 'DUPLEX_HOME')], default='True', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='state',
            field=models.CharField(choices=[('KARANATAKA', 'KARANATAKA'), ('DEHLI', 'DEHLI'), ('HARIYANA', 'HARIYANA'), ('KERALA', 'KERALA'), ('TAMILNADU', 'TAMILNADU'), ('ANDHRA PRADESH', 'ANDHRA PRADESH'), ('TELANGANA', 'TELANGANA'), ('BIHARA', 'BIHARA'), ('MADHYA PRADESH', 'MADHYA PRADESH'), ('PUNJAB', 'PUNJBA'), ('GOA', 'GOA'), ('J&K', 'J&K'), ('Assam', 'ASSAM'), ('Chhattisgarh', 'CHHATTISGARH'), ('GUJARAT', 'GUJARAT'), ('Himachal Pradesh', 'HIMACHAL PRADESH'), ('Haryana', 'HARYANA'), ('Jharkhand', 'JHARKHAND'), ('Maharashtra', 'MAHARASHTA'), ('Manipur', 'MANIPUR'), ('Meghalaya', 'MEGHALAYA'), ('Mizoram', 'MIZORAM'), ('Nagaland', 'NAGALAND'), ('Odisha', 'ODISHA')], default=True, max_length=10),
        ),
    ]
