# Generated by Django 2.1.4 on 2018-12-19 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
        ('termination', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='securiyt_refund',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('refund_amount', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('refund_reason', models.TextField()),
                ('employee_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_id+', to='employee.employee')),
                ('termination_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terminationid+', to='termination.termination')),
            ],
        ),
    ]
