# Generated by Django 2.1.3 on 2018-12-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='Phone',
            field=models.BigIntegerField(),
        ),
    ]
