# Generated by Django 2.1.4 on 2018-12-08 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='checkpayment',
            fields=[
                ('bankname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('accno', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='creditcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holdername', models.CharField(max_length=100)),
                ('accountype', models.CharField(max_length=100)),
                ('expdate', models.IntegerField()),
                ('accno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accno+', to='trancations.checkpayment')),
                ('bankname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bankname+', to='trancations.checkpayment')),
            ],
        ),
        migrations.CreateModel(
            name='trancations',
            fields=[
                ('paymentid', models.AutoField(primary_key=True, serialize=False)),
                ('paymentdate', models.DateField()),
                ('paymentamount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paymentmethod', models.CharField(choices=[('cash', 'CASH'), ('check', 'CHECK'), ('creditcard', 'CREDITCARD')], default='True', max_length=10)),
            ],
        ),
    ]
